<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$this->metaTitle?></title>
<meta name="keywords" content="<?=$this->metaKeywords?>" />
<meta name="description" content="<?=$this->metaDescription?>" />
<link rel="shortcut icon" href="/images/ACTIVE.ico" />
<link rel="stylesheet" type="text/css" href="/css/page-format.css"/>
<link rel="stylesheet" type="text/css" href="/css/stylesheet.css" />
<link rel="stylesheet" type="text/css" href="/css/topnav.css"/>
<link rel="stylesheet" type="text/css" href="/css/subnav-dropdown.css"/>
<!-- <link rel="stylesheet" type="text/css" href="/css/subnav-sidebar.css"/> -->
<script type="text/javascript" src="/js/jquery-1.4.4.js"></script>
<script type="text/javascript" src="/js/jquery.easing.1.3.js"></script>
<?php foreach ($this->css as $css):?>
    <link rel="stylesheet" type="text/css" href="<?=htmlentities($css, ENT_QUOTES, 'UTF-8')?>" />
<?php endforeach;?>
<?php foreach ($this->headJs as $headJs):?>
    <script src="<?=htmlentities($headJs, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</head>

<body>

<div id="main_wrapper">

<div id="header_wrapper">
    Header
</div>

<div id="header_images">
	<?php $i = 1; foreach($this->header_images as $image): ?>
	<?php if($image['url']): ?><a href="<?=$image['url']?>" target="_blank"><?php endif; ?>
    <div class="imagewrapper<?=($i == count($this->header_images)) ? ' last' : ''?>"><img width="176" height="176" src="/images/header-images/<?=$image['image']?>" alt="" />
    </div>
    <?php if($image['url']): ?></a><?php endif; ?>
    <?php $i++; endforeach; ?>
</div>

<div id="nav_wrapper">
	<div id="topnav">
    	<ul id="mainnav">
        	<?=$this->nav?>
    	</ul>
    </div>
</div>

<div id="content_wrapper">
	<div id="text_wrapper">
		<?=$this->page_title ? '<h1>' . $this->page_title . '</h1>' : '';?>
			<?php
            if ($this->contentView):
                if ($file = $this->_script($this->contentView)):
                        include $file;
                endif;
            else:
                echo $this->content;
            endif;
        	?>
	</div>
	<div id="content_left">
        Content Left
	</div>
    <div id="content_right">
    	Content Right
    </div>
</div>

<div id="latest_news">
	<h2>latest news</h2>
    <div id="news_items">
    	<?php if(count($this->newsitems)): ?>
                   
        	<?php foreach($this->newsitems as $newsitem): ?>
            <p style="display: none;"><?=date('jS F Y', strtotime($newsitem['newsdate']))?></p>
            <h4 style="margin-bottom: 3px;"><?=$newsitem['title']?></h4>
            <p style="margin-bottom: 0px;"><?=$newsitem['preview']?></p>
            <h5 style="margin-top: -5px;"><a href="/news/view/article/<?=$newsitem['news_id']?>">read full article here...</a></h5>
            <?php endforeach; ?>
                    
        <?php else: ?>
            <p>No news items found</p>
        <?php endif; ?>
	</div>
</div>

<div id="blog_home">
	<h1>latest from our blog...</h1>
	<?php if(count($this->blogposts)): ?>
		<?php foreach($this->blogposts as $blogposts): ?>
	<div id="blogListImage">
		<a href="/blog/view/<?=$blogposts['post_id']?>"><img style="margin-bottom: 10px;" src="/images/blogimages/<?=$blogposts['post_image']?>" width="210" alt="<?=$blogposts['post_title']?>" /></a>
	</div>
	<div id="blogListContent">
		<h4><a href="/blog/view/<?=$blogposts['post_id']?>"><?=$blogposts['post_title']?></a></h4>
		<p><?=$blogposts['post_summary']?></p>
		<h5><a href="/blog/view/<?=$blogposts['post_id']?>">read full article here...</a></h5>
	</div>
	<div id="clear"></div>
	<?php endforeach; ?>
	<?php else: ?>
        <p>No blog posts found</p>
    <?php endif; ?>
</div><!-- end id="blog_home" -->

<div id="footer_wrapper">
	Footer
</div>

</div>

<?php foreach ($this->js as $js):?>
    <script src="<?=htmlentities($js, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</body>
</html>